KS-7-1 added cycle for and randomizer of char
morganharry/KotlinSprint pull request #34
Opened 2023-07-14 07:50 UTC by morganharry

2023-07-14 17:58 UTC, ievetrov requested changes

2023-07-14 17:58 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +package lesson_7
а зачем ты в этот мр положил все файлы для остальных заданий?) оставь только первый файлик

2023-07-14 17:58 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    for (i in 1..6) {
в задании было сказано что для каждого символа нужно создать отдельную переменную) так что тут можно без цикла обойтись

2023-07-15 01:36 UTC, morganharry commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    for (i in 1..6) {
Исправил, с циклом мне кажется решение было изящнее)

2023-07-15 04:37 UTC, morganharry commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +package lesson_7
+

2023-07-15 07:34 UTC, ievetrov requested changes

2023-07-15 07:34 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    val char1 = range.random()
в данном случае у тебя символы пароля не будут чередоваться) должно быть `буква.цифра.буква.цифра...`)

2023-07-15 07:34 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    println(char1.toString() + char2 + char3 + char4 + char5 + char6)
и принт тут можно сделать красивее без плюсов)

2023-07-15 07:34 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson7_task1.kt
> +    for (i in 1..6) {
согласен, но с ТЗ не поспоришь)

2023-07-16 08:35 UTC, ievetrov approved these changes

2023-07-16 12:29 UTC, merged