KS-7-2 added cycle for and randomizer of number
morganharry/KotlinSprint pull request #35
Opened 2023-07-14 08:02 UTC by morganharry

2023-07-14 18:00 UTC, ievetrov requested changes

2023-07-14 18:00 UTC, ievetrov commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +        if (userCode == smsCode) println("Добро пожаловать.")
можно убрать этот `if` и `println("Добро пожаловать.")` перенести за цикл `while`) тогда не будет лишней проверки

2023-07-15 01:41 UTC, morganharry commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +        if (userCode == smsCode) println("Добро пожаловать.")
Вынес из цикла позитивный результат.  Но проверка осталась - для отрицательного результата.

2023-07-15 07:34 UTC, ievetrov approved these changes

2023-07-15 09:29 UTC, merged