KS-10-2 added fun checker and cycle
morganharry/KotlinSprint pull request #49
Opened 2023-07-17 10:39 UTC by morganharry

2023-07-17 16:28 UTC, ievetrov requested changes

2023-07-17 16:28 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson10_task2.kt
> +fun loginAndPswChecker(str: String): Boolean {
Более распространенной хорошей практикой является использование глагола в названии методов. Например, checkLoginAndPasswordLength()

2023-07-17 16:28 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson10_task2.kt
> +    return if (str.length < MIN_LENGTH) {
предлагаю здесь сразу возвращать результат условия без использования return

2023-07-17 17:26 UTC, morganharry commented on src/main/kotlin/lesson_10/lesson10_task2.kt
> +    return if (str.length < MIN_LENGTH) {
без return:
fun checkLoginAndPasswordLength (str: String) = (str.length < MIN_LENGTH)
Но вот куда println в таком случае деть? Обратно в цикл бессмысленно. 
Ума не приложу, как без return вывод еще оставить в функции. I need help.

2023-07-17 20:13 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson10_task2.kt
> +    return if (str.length < MIN_LENGTH) {
if тоже умеет возвращать результаты условий внутри себя)

```
fun loginAndPswChecker(str: String) = if (str.length < MIN_LENGTH) {
    println("Логин или пароль недостаточно длинные")
    true
} else {
    println("Логин или пароль одобрены")
    false
} 
```

2023-07-18 14:21 UTC, ievetrov approved these changes
отлично!

2023-07-18 15:05 UTC, merged