KS-11-3 added classes (properties, methods)
morganharry/KotlinSprint pull request #56
Opened 2023-07-20 07:24 UTC by morganharry

2023-07-21 04:13 UTC, ievetrov requested changes

2023-07-21 04:13 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        val loginsList = mutableListOf<String>()
а зачем тебе тут лист если у тебя уже есть сет юзеров? можно было бы сделать проще:
`fun roomView():String =("\t- обложка: $cover, название: $name, участники: ${usersList.joinToString(",")}")`

2023-07-21 04:13 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +class Rooms(
классы лучше называть в единственном числе)

2023-07-21 04:13 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    val usersList: MutableSet<UsersCl>,
здесь кажется что можно обойтись обычным сетом, вроде бы он нигде не изменяется)

2023-07-21 04:13 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +class UsersCl (
также лучше изменить название на единственное число

2023-07-21 06:24 UTC, morganharry commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        val loginsList = mutableListOf<String>()
Потому что я хочу результат с перечнем login через запятую:
	- обложка: Smile.jpg, название: jokes, участники: **North1955,WestTT**
А в варианте с usersList, т.к. он не String, а User, то выходит:
	- обложка: Smile.jpg, название: jokes, участники: **lesson_11.User@1ddc4ec2,lesson_11.User@133314b**
	
Понимаю, что неоптимальное решение предложил, но это единственное рабочее, которое пришло мне в голову.

2023-07-21 06:32 UTC, morganharry commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    val usersList: MutableSet<UsersCl>,
Ну теоретически закладывал сюда возможность добавления уникальных пользователей в Room. Но в рамках задачи это конечно не предусмотрено. Да и уникальность тут, я так понимаю, условная - на уровне названия переменной, что в принципе позволяет создать двух пользователей с одинаковым login. По сути бесполезно, правильно?
наверное сразу лучше в ListOf?

2023-07-22 05:42 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        val loginsList = mutableListOf<String>()
чтобы получить логины из объектов юзеров можно сделать таким образом:
`${usersList.map{ it.login }.joinToString(",")`

мы как бы проходимся по списку и достаем из него логин каждого)

2023-07-22 05:44 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    val usersList: MutableSet<UsersCl>,
да тут можно сделать обычный лист) если нужно будет его модифицировать, то в дальнейшем можно будет сделать функцию для этого

2023-07-22 05:45 UTC, ievetrov requested changes

2023-07-22 05:45 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    val usersList: Set <User>,
переделать на лист)

2023-07-23 04:13 UTC, ievetrov approved these changes

2023-07-23 04:20 UTC, merged