KS-11-4 added class (properties, methods)
morganharry/KotlinSprint pull request #57
Opened 2023-07-20 14:12 UTC by morganharry

2023-07-21 03:40 UTC, morganharry commented
Была идея объекты Контакты близких людей сделать классом  Contact, но это вызывает ошибку. Если это входит в рамки задачи, то тут хотелось бы ликбез - можно ли добавлять объект внутри класса того же класса?

2023-07-21 06:46 UTC, ievetrov commented
> Была идея объекты Контакты близких людей сделать классом Contact, но это вызывает ошибку. Если это входит в рамки задачи, то тут хотелось бы ликбез - можно ли добавлять объект внутри класса того же класса?

так нельзя делать, но ты можешь сделать класс близких людей и уже его прикреплять к контакту

2023-07-21 06:49 UTC, ievetrov requested changes

2023-07-21 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    var closePeople1: String = "username",
было бы красивее сделать отдельный класс близкого человека, а здесь хранить массив этих объектов, тогда в случае когда у контакта больше 3 близких людей будет все правильно работать)

2023-07-21 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson11_task4.kt
> +    var iCloud: String = "",
было бы неплохо сделать проверку на корректность ввода номера телефона и почты)

2023-07-22 19:05 UTC, ievetrov approved these changes

2023-07-23 01:42 UTC, merged