KS-14-1 added class with properties amd fun's
morganharry/KotlinSprint pull request #70
Opened 2023-07-25 04:25 UTC by morganharry

2023-07-25 16:35 UTC, ievetrov requested changes

2023-07-25 16:35 UTC, ievetrov commented on src/main/kotlin/lesson_14/lesson14_task1.kt
> +    val capacity: Int,
а если мы хотим создать ледокол, как можно это сделать?)

2023-07-26 18:02 UTC, ievetrov requested changes

2023-07-26 18:02 UTC, ievetrov commented on src/main/kotlin/lesson_14/lesson14_task1.kt
> +    var fuelLevel: Int,
а как мы сможем определить что этот корабль может колоть лед? нагляднее было бы добавить в `Ship` булевскую переменную, которая бы однозначно определяла может ли корабль колоть лед)

2023-07-27 02:38 UTC, morganharry commented on src/main/kotlin/lesson_14/lesson14_task1.kt
> +    val capacity: Int,
Добавил свойство, убрал классы. не сразу вкурил задание.

2023-07-27 16:06 UTC, ievetrov approved these changes

2023-07-27 16:56 UTC, merged