KS-19-4 added enum and class with fun's
morganharry/KotlinSprint pull request #96
Opened 2023-08-02 10:51 UTC by morganharry

2023-08-03 04:59 UTC, ievetrov requested changes

2023-08-03 04:59 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +            when (readln()) {
все ок, только давай дадим пользователю вводить строки в любом регистре)

2023-08-04 06:49 UTC, ievetrov requested changes

2023-08-04 06:49 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +            when {
нужно исправить этот `when`, так как сейчас любой ввод цвета (даже без учета регистра) выдает `Указан некорректный тип`. при этом дальше по коду выдается сообщение что заряжен патрон синего цвета) 

возможно в `enum` стоит добавить поле не заряжен, либо флаг к танку, тогда после выстрела это поле бы сбрасывалось

2023-08-04 13:42 UTC, morganharry commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +            when {
![image](https://github.com/morganharry/KotlinSprint/assets/101452247/e30d02e4-b71a-437f-9a41-5864ec45ae38)
Блин, у меня всё чётко.

2023-08-04 14:14 UTC, morganharry commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +            when {
флаг сделал (так как я его понял). По when вроде норм отрабатывает, посмотри еще раз, плиз.

2023-08-05 07:21 UTC, ievetrov approved these changes

2023-08-05 07:21 UTC, ievetrov commented on src/main/kotlin/lesson_19/lesson19_task4.kt
> +            when {
да, теперь все отлично)

2023-08-05 10:59 UTC, merged